# Generated by Django 5.0.13 on 2025-04-07 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('departamento', models.CharField(max_length=50)),
                ('pueesto', models.CharField(max_length=50)),
                ('salario_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_contratacion', models.DateField()),
                ('estatus', models.CharField(default='Activo', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ModuloA',
            fields=[
                ('modulo_id', models.AutoField(primary_key=True, serialize=False)),
                ('modulo_nombre', models.CharField(max_length=50)),
                ('modulo_desc', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Asistencias',
            fields=[
                ('asistencia_id', models.AutoField(primary_key=True, serialize=False)),
                ('asistencia_fecha', models.DateField()),
                ('asistencia_h_entrada', models.TimeField()),
                ('asistencia_h_salida', models.TimeField(blank=True, null=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Nomina',
            fields=[
                ('nomina_id', models.AutoField(primary_key=True, serialize=False)),
                ('nomina_sueldo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nomina_horasextra', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('nomina_bono', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('nomina_incentivos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('nomina_isr', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('nomina_iggs', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('nomina_irtra', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('nomina_tipo', models.CharField(choices=[('Mensual', 'Mensual'), ('Semanal', 'Semanal'), ('Quincenal', 'Quincenal')], max_length=10)),
                ('nom_fecha', models.DateField()),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Prestaciones',
            fields=[
                ('prestacion_id', models.AutoField(primary_key=True, serialize=False)),
                ('prestacion_tipo', models.CharField(max_length=50)),
                ('prestacion_monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Productividad',
            fields=[
                ('Productivo_id', models.AutoField(primary_key=True, serialize=False)),
                ('inpro_TC', models.IntegerField()),
                ('inpro_horasT', models.IntegerField()),
                ('inpro_ev', models.DecimalField(decimal_places=2, max_digits=5)),
                ('emplaod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('reporte_id', models.AutoField(primary_key=True, serialize=False)),
                ('reporte_tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('reporte_desc', models.TextField()),
                ('reporte_fecha', models.DateField()),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.empleado')),
            ],
        ),
    ]
