# Generated by Django 5.0.13 on 2025-03-21 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_departamento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id_puesto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('fecha_contratacion', models.DateField()),
                ('estatus', models.CharField(default='Activo', max_length=20)),
                ('id_departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.departamento')),
                ('id_puesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.puesto')),
            ],
        ),
    ]
