# Generated by Django 5.0.13 on 2025-04-07 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Nomina',
        ),
    ]
