# Generated by Django 5.0.13 on 2025-04-07 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_delete_nomina'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nomina',
            fields=[
                ('nomina_id', models.AutoField(primary_key=True, serialize=False)),
                ('nomina_sueldo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nomina_horasextra', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('nomina_bono', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('nomina_incentivos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('nomina_isr', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('nomina_iggs', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('nomina_irtra', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('nomina_tipo', models.CharField(choices=[('Mensual', 'Mensual'), ('Semanal', 'Semanal'), ('Quincenal', 'Quincenal')], max_length=10)),
                ('nom_fecha', models.DateField()),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.empleado')),
            ],
        ),
    ]
