# Generated by Django 5.0.13 on 2025-04-08 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_nomina'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nomina',
            name='nomina_irtra',
        ),
    ]
