# Generated by Django 5.0.13 on 2025-03-26 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_empleado_departamento_empleado_puesto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='departamento',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empleado',
            name='puesto',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='empleado',
            name='salario_base',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Departamento',
        ),
        migrations.DeleteModel(
            name='Puesto',
        ),
    ]
