# Generated by Django 5.0.13 on 2025-05-09 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_remove_nomina_nomina_irtra'),
    ]

    operations = [
        migrations.CreateModel(
            name='indemnizacion',
            fields=[
                ('indem_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_contratacion', models.DateField()),
                ('fecha_terminacion', models.DateField()),
                ('motivo', models.CharField(max_length=150)),
                ('salario_promedio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Calculo_indemnizacion', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateField()),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='prestacion_dias',
            fields=[
                ('prestacion_dias_id', models.AutoField(primary_key=True, serialize=False)),
                ('dias_disponibles', models.IntegerField()),
                ('dias_tomados', models.IntegerField(default=0)),
                ('fecha_solicitud', models.DateField()),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobada', 'Aprobada'), ('Rechazada', 'Rechazada'), ('Tomados', 'Tomados')], default='Pendiente', max_length=10)),
                ('fecha_aprobacion', models.DateField(blank=True, null=True)),
                ('fecha_rechazo', models.DateField(blank=True, null=True)),
                ('motivo_rechazo', models.CharField(blank=True, max_length=150, null=True)),
                ('periodo', models.IntegerField(blank=True, null=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.empleado')),
            ],
        ),
    ]
