# Generated by Django 5.0.13 on 2025-03-27 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_empleado_departamento_alter_empleado_puesto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='puesto',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='salario_base',
        ),
    ]
