# Generated by Django 5.0.13 on 2025-05-10 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_indemnizacion_prestacion_dias'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='estado_indemnizacion',
            field=models.IntegerField(default=0),
        ),
    ]
