# Generated by Django 5.0.13 on 2025-03-27 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_remove_empleado_departamento_remove_empleado_puesto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='departamento',
            field=models.CharField(default='guatemala', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleado',
            name='pueesto',
            field=models.CharField(default='gerente', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleado',
            name='salario_base',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=10),
            preserve_default=False,
        ),
    ]
