# Generated by Django 5.0.13 on 2025-05-13 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_empleado_estado_indemnizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomina',
            name='nomina_bono',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
