# Generated by Django 5.0.13 on 2025-05-23 03:19

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_usuario_empleado_dias_descanso'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomina',
            name='bono_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
