# Generated by Django 5.0.13 on 2025-05-23 21:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_nomina_bono_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productividad',
            old_name='emplaod',
            new_name='empleado',
        ),
        migrations.AddField(
            model_name='productividad',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
